### ISSUE TITLE
[FEATURE]: Automation pause on staff selection menu

### ISSUE THREAD

**Issue by alvinlor2001** [COMP3122-2324-Project/Simpsyber#45]
I have a suggestion for the game. Currently, when I select staff for a task, the game doesn't stop automatically. However, the time that staff members spend idle is really important for the game's outcome. This means I have to manually pause the game while choosing staff, which makes the game experience frustrating. It would be much better if the game automatically paused when I'm selecting staff so I can focus on making the right choices without worrying about time management.

**Comment by lhm277** [comment]
I completely agree with this suggestion. It would be a great enhance to the game experience if the time can be automatically paused when selecting staff for a task. This would allow players to focus on making the choices with less steps of pausing and continuing the timer.

However, I noticed that this suggestion has been previously brought up by others, and I believe it's worth considering as it has received positive feedback. For more information about this feature request, please refer to https://github.com/COMP3122-2324-Project/Simpsyber/issues/11.

I believe that implementing this enhancement would improve the gameplay flow, which is essential to prioritise this feature to provide a smoother and more enjoyable gaming experience for all players.

**Comment by alvinlor2001** [comment]
Thank you for bringing this similar feature recommendation to my attention. I had actually come across #11, which proposes using a hotkey to pause the game before I post my comment. While the idea of a hotkey is a step in the right direction, it still requires manual intervention from the player.

My suggestion, on the other hand, is to have the game automatically pause during staff selection, eliminating the need for any manual tasks. Although both suggestions revolve around pausing, our ideas differ in their approach and implementation.

**Comment by alvinlor2001** [comment]
Thank you for bringing this similar feature recommendation to my attention. I had actually come across suggestion #11, which proposed using a hotkey to pause the game, before I posted my comment. However, I did not check the comments below, so I didn't notice that my idea had already been mentioned by others. Again, thank you for announcing, and I will make a new feature idea.
