### ISSUE TITLE
[DEFECT] Lagging Experience During Gameplay

### ISSUE THREAD

**Issue by alvinlor2001** [COMP3122-2324-Project/Simpsyber#47]
I've been experiencing a frustrating issue while playing the game on Chrome. Whenever I launch the game, my CPU usage spikes to 100% and my computer becomes extremely laggy. However, when I switch to using Edge, the gameplay becomes smooth and lag-free. It's quite perplexing to encounter such a stark difference between the two browsers.

![未命名](https://github.com/COMP3122-2324-Project/Simpsyber/assets/30236827/80ef4262-2c12-4cd9-b238-6f0c37bce47c)

**Comment by LeungYatOn** [comment]
I found the similiar problem too. I fixed in the setting of Chrome. Follow my steps in the video.

setting -> search ("使用圖形加速功能 (如果可用)") -> turn it on -> restart your Chrome

https://github.com/COMP3122-2324-Project/Simpsyber/assets/157469522/76cb3e00-a91d-4956-ac5b-571c63161466

**Comment by alvinlor2001** [comment]
Thank you, the problem has been resolved!

I discovered that I only enabled the graphic acceleration in Microsoft Edge, while it is disabled in Chrome. Consequently, the laggy experience only occurs in Chrome.
